# Generated by Django 3.2.6 on 2021-08-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='qoutedate',
            new_name='quotedate',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='qouteprice',
            new_name='quoteprice',
        ),
    ]
